In [1]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix


In [2]:
df = pd.read_csv('./uci_malware_detection.csv')

In [3]:
df

Label  F_1  F_2  F_3  F_4  F_5  F_6  F_7  F_8  F_9  ...  F_522  \
0    non-malicious    1    0    1    0    1    0    1    0    1  ...      0   
1    non-malicious    1    0    1    0    1    0    1    0    1  ...      0   
2    non-malicious    1    0    1    0    1    0    1    0    1  ...      0   
3    non-malicious    1    0    1    0    1    0    1    0    1  ...      0   
4    non-malicious    1    0    1    0    1    0    1    0    1  ...      0   
..             ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...   
368      malicious    1    0    1    0    1    0    1    0    1  ...      0   
369      malicious    1    0    1    0    1    0    1    0    1  ...      0   
370      malicious    1    0    1    0    1    0    1    0    1  ...      1   
371      malicious    1    0    1    0    1    0    1    0    1  ...      0   
372      malicious    1    0    1    0    1    0    1    0    1  ...      0   

     F_523  F_524  F_525  F_526  F_527  F_528  F_529  F_530  F_531  
0        0      0      0      0      0      0      0      0      0  
1        0      0      0      0      0      0      0      0      0  
2        0      0      0      0      0      0      0      0      0  
3        0      0      0      0      0      0      0      0      0  
4        0      0      0      0      0      0      0      0      0  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
368      0      0      0      0      0      0      1      0      1  
369      0      0      1      0      0      0      0      1      0  
370      0      0      0      1      0      0      0      1      0  
371      0      0      0      1      0      0      0      1      0  
372      0      0      1      0      0      0      0      0      1  

[373 rows x 532 columns]

In [4]:
y = df['Label']

In [5]:
y

0      non-malicious
1      non-malicious
2      non-malicious
3      non-malicious
4      non-malicious
           ...      
368        malicious
369        malicious
370        malicious
371        malicious
372        malicious
Name: Label, Length: 373, dtype: object

In [6]:
df.columns.drop('Label')

Index(['F_1', 'F_2', 'F_3', 'F_4', 'F_5', 'F_6', 'F_7', 'F_8', 'F_9', 'F_10',
       ...
       'F_522', 'F_523', 'F_524', 'F_525', 'F_526', 'F_527', 'F_528', 'F_529',
       'F_530', 'F_531'],
      dtype='object', length=531)

In [7]:
X = df[df.columns.drop('Label')]

In [8]:
X

F_1  F_2  F_3  F_4  F_5  F_6  F_7  F_8  F_9  F_10  ...  F_522  F_523  \
0      1    0    1    0    1    0    1    0    1     0  ...      0      0   
1      1    0    1    0    1    0    1    0    1     0  ...      0      0   
2      1    0    1    0    1    0    1    0    1     0  ...      0      0   
3      1    0    1    0    1    0    1    0    1     0  ...      0      0   
4      1    0    1    0    1    0    1    0    1     0  ...      0      0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...   ...  ...    ...    ...   
368    1    0    1    0    1    0    1    0    1     0  ...      0      0   
369    1    0    1    0    1    0    1    0    1     0  ...      0      0   
370    1    0    1    0    1    0    1    0    1     0  ...      1      0   
371    1    0    1    0    1    0    1    0    1     0  ...      0      0   
372    1    0    1    0    1    0    1    0    1     0  ...      0      0   

     F_524  F_525  F_526  F_527  F_528  F_529  F_530  F_531  
0        0      0      0      0      0      0      0      0  
1        0      0      0      0      0      0      0      0  
2        0      0      0      0      0      0      0      0  
3        0      0      0      0      0      0      0      0  
4        0      0      0      0      0      0      0      0  
..     ...    ...    ...    ...    ...    ...    ...    ...  
368      0      0      0      0      0      1      0      1  
369      0      1      0      0      0      0      1      0  
370      0      0      1      0      0      0      1      0  
371      0      0      1      0      0      0      1      0  
372      0      1      0      0      0      0      0      1  

[373 rows x 531 columns]

In [9]:
y

0      non-malicious
1      non-malicious
2      non-malicious
3      non-malicious
4      non-malicious
           ...      
368        malicious
369        malicious
370        malicious
371        malicious
372        malicious
Name: Label, Length: 373, dtype: object

In [10]:
# Separar los dataset (X,y) en 2 datasets: (X_train, y_train) y (X_test, y_test)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [11]:
X_train

F_1  F_2  F_3  F_4  F_5  F_6  F_7  F_8  F_9  F_10  ...  F_522  F_523  \
36     1    0    1    0    1    0    1    0    1     0  ...      0      0   
158    1    0    1    0    1    0    1    0    1     0  ...      0      0   
183    1    0    1    0    1    0    1    0    1     0  ...      0      0   
168    1    0    1    0    1    0    1    0    1     0  ...      0      1   
302    1    0    1    0    1    0    1    0    1     0  ...      0      1   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...   ...  ...    ...    ...   
71     1    0    1    0    1    0    1    0    1     0  ...      0      0   
106    1    0    1    0    1    0    1    0    1     0  ...      0      0   
270    1    0    1    0    1    0    1    0    1     0  ...      0      0   
348    1    0    1    0    1    0    1    0    1     0  ...      0      0   
102    1    0    1    0    1    0    1    0    1     0  ...      0      0   

     F_524  F_525  F_526  F_527  F_528  F_529  F_530  F_531  
36       0      0      0      0      0      0      0      0  
158      0      0      0      0      0      0      0      1  
183      0      0      1      0      0      0      1      0  
168      0      0      1      0      0      1      0      0  
302      0      0      1      0      0      0      1      0  
..     ...    ...    ...    ...    ...    ...    ...    ...  
71       0      0      0      0      0      0      0      0  
106      0      0      0      0      0      0      0      0  
270      0      0      1      0      0      0      1      0  
348      0      0      1      0      0      0      1      0  
102      0      0      0      0      0      0      0      1  

[249 rows x 531 columns]

In [12]:
y_train

36     non-malicious
158        malicious
183        malicious
168        malicious
302        malicious
           ...      
71     non-malicious
106        malicious
270        malicious
348        malicious
102        malicious
Name: Label, Length: 249, dtype: object

In [13]:
clf = DecisionTreeClassifier()

In [14]:
clf

DecisionTreeClassifier()

In [15]:
clf = clf.fit(X_train, y_train)

In [16]:
y_pred = clf.predict(X_test)

In [17]:
y_test == y_pred

327    True
33     True
15     True
314    True
57     True
       ... 
104    True
285    True
118    True
352    True
31     True
Name: Label, Length: 124, dtype: bool

In [18]:
confusion_matrix(y_test, y_pred)

array([[94,  4],
       [ 1, 25]])

In [20]:
# Version 2:

In [19]:
import pandas as pd
import numpy as np
import pickle

from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import confusion_matrix


In [21]:
# recuerda que el error de module not found se puede deber a que te falta instalar librerias
# prueba a instalar las que faltan con:

# pip install scikit-learn 
# pip install pandas


# puede que necesites poner ! delante de pip (!pip install <paquete>)

In [22]:
def evaluate_model(model, X_train, X_test, y_train, y_test):
    print(model.__class__)
    result = clf.score(X_test, y_test)
    print(f"Accuracy test: {round(100 * result, 2)}% \n")
    result = clf.score(X_train, y_train)
    print(f"Accuracy train: {round(100 * result, 2)}% \n")


    y_pred_test = clf.predict(X_test)
    print("Test confusion matrix")
    print(confusion_matrix(y_test, y_pred_test))

    print("")

    y_pred_train = clf.predict(X_train)
    print("Train confusion matrix")
    print(confusion_matrix(y_train, y_pred_train))



In [23]:
# lectura del dataset
df = pd.read_csv(r"./uci_malware_detection.csv")

# Extraccion de variables 
X = df.drop("Label", axis=1)
# Etiquetas (malware / no-malware)
y = df["Label"]  # variable objetivo


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)


clf_tree = tree.DecisionTreeClassifier()
clf_forest = RandomForestClassifier()
clf_knn = KNeighborsClassifier(n_neighbors=3)

for clf in [clf_tree, clf_knn, clf_forest]:
    clf = clf.fit(X_train, y_train)
    evaluate_model(clf, X_train, X_test, y_train, y_test)
    print(" ")

# save the model to disk
# filename = 'finalized_model.pkl'
#pickle.dump(clf, open(filename, 'wb'))



# some time later...

# load the model from disk
#loaded_model = pickle.load(open(filename, 'rb'))




<class 'sklearn.tree._classes.DecisionTreeClassifier'>
Accuracy test: 95.54% 

Accuracy train: 100.0% 

Test confusion matrix
[[85  4]
 [ 1 22]]

Train confusion matrix
[[212   0]
 [  0  49]]
 
<class 'sklearn.neighbors._classification.KNeighborsClassifier'>
Accuracy test: 97.32% 

Accuracy train: 98.85% 

Test confusion matrix
[[88  1]
 [ 2 21]]

Train confusion matrix
[[212   0]
 [  3  46]]
 
<class 'sklearn.ensemble._forest.RandomForestClassifier'>
Accuracy test: 98.21% 

Accuracy train: 100.0% 

Test confusion matrix
[[88  1]
 [ 1 22]]

Train confusion matrix
[[212   0]
 [  0  49]]
 
